EAR 2033 page description redesign
ONSdigital/eq-publisher-v3 pull request #160
Opened 2023-04-25 06:34 UTC by farres1

2023-05-02 15:28 UTC, Paul-Joel commented on src/eq_schema/schema/Section/index.js
> +    ) {
SHouldn't this also check for the presence of section.introductionPageDescription, otherwise if could be trying to use a value it doesn't have?

2023-05-02 15:30 UTC, Paul-Joel requested changes
Question on value check

2023-05-03 09:39 UTC, Paul-Joel approved these changes

2023-05-03 09:46 UTC, sudeepkunhis approved these changes

2023-05-03 09:48 UTC, merged