Fix list collector answer codes
ONSdigital/eq-publisher-v3 pull request #200
Opened 2023-12-13 13:03 UTC by farres1

> ### BEFORE MAKING YOUR PR
>
> Please ensure:
>
> - There are no linting errors, all tests must pass
> - PR is named after JIRA ticket number e.g. EAR-###
> - **Accesibility** checks are completed:
>   - Elements have discernible and consistent focus states
>   - Elements can be navigated to and used by just a keyboard
>   - Elements and text can be read out by a screen reader, and the descriptions are understandable
> - Your feature / bug fix works across **GCP** and **AWS** (where appropriate)
>   - Are modifications to eq-publisher-v3 required?
>   - Are modifications to the Firestore data source required?

---

### What is the context of this PR?

Fix answer_codes for list collector qualifier and confirmation pages to match their answer IDs

### How to review
**Check:**
- [ ] Qualifier (driving) answers' `answer_id` in the `answer_codes` array matches the qualifier (driving) answer's ID in the schema
- [ ] Confirmation (add another) answers' `answer_id` in the `answer_codes` array matches the confirmation (add another) answer's ID in the schema
- [ ] Other `answer_id`s in the `answer_codes` array are unchanged
- [ ] Questionnaires with list collector and non-list-collector pages can be viewed and completed without errors

### What to do after everything is green

1. - [ ] Bring this branch up-to-date with Origin/Master
2. - [ ] If there are a lot of commits or some are not helpful to read, squash them down
3. - [ ] Click the **Merge** button on this pull request
4. - [ ] Does this change mean the **Capability examples** questionnaire should be updated?
5. - [ ] Move the Jira ticket for this task into the next stage of the process

2023-12-13 13:32 UTC, martyncolmer requested changes

2023-12-13 13:32 UTC, martyncolmer commented on src/eq_schema/block-types/listCollector/drivingQuestion.js
> +        id: `answer-driving-${page.answers[0].id}`,
This no longer needs to be prefixed with 'answer-driving', it can be just 'answer' like all other answers.

2023-12-15 12:57 UTC, martyncolmer approved these changes

2023-12-15 13:04 UTC, kayloshai approved these changes

2023-12-15 13:04 UTC, merged