EAR-1408 Implement new routing rules for publisher v3
ONSdigital/eq-publisher-v3 pull request #49
Opened 2021-08-12 13:32 UTC by ashtuck

What is the context of this PR?

New routing rules for v3 of publisher. This is matching the new routing rules `https://github.com/ONSdigital/eq-questionnaire-validator/blob/master/schemas/common_definitions.json`.

How to review

Right now there isn’t a way to test as Runner hasn’t been updated yet. The only thing that can be done is matching it to the new schema. 

What to do after everything is green
    *   Bring this branch up-to-date with Origin/Master
    *   If there are a lot of commits or some are not helpful to read, squash them down
    *   Click the Merge button on this pull request
    *   Does this change mean the Capability examples questionnaire should be updated?
    *   Move the Jira ticket for this task into the next stage of the process

2021-08-17 08:00 UTC, MattElcock approved these changes

2021-08-17 08:12 UTC, ashtuck commented
Just adding a comment to this 'cos i didn't make it clear in the initial PR, once this has been approved we can't merge into master until Runner has been updated.

2021-09-06 11:00 UTC, martyncolmer requested changes
Expressions

Number answer
Unanswered - not ok, it should ignore any set value and use null i.e “==“ {value_source, null}

Radio option
One-of - should translate to “any-in” not “equals any”
Unanswered should be “==“ not “!=“

Checkbox
Not any of should translate to “not" { “any-in” …….}  not “anyOf”
Unanswered should be “==“ not “!=“

2022-03-31 12:54 UTC, farres1 approved these changes

2022-03-31 14:05 UTC, martyncolmer approved these changes

2022-03-31 14:39 UTC, zimboflyman approved these changes

2022-03-31 14:55 UTC, merged